// SPDX-License-Identifier: AGPL-3.0-only
#if canImport(Security)
import Foundation
import Security

/// Validates the RSA-2048/4096 PKCS#10 format generated by the pinned CSRBuilder.
/// Uses Security for key parsing and signature verification. Key equality is
/// NOT a certificate-chain trust decision or proof of Apple issuance.
public enum CertificateKeyBinding {
    private static let rsaAlgorithm = Data([0x30,0x0d,0x06,0x09,0x2a,0x86,0x48,0x86,0xf7,0x0d,0x01,0x01,0x01,0x05,0x00])
    private static let sha256RSA = Data([0x30,0x0d,0x06,0x09,0x2a,0x86,0x48,0x86,0xf7,0x0d,0x01,0x01,0x0b,0x05,0x00])

    public static func validate(privateKeyPEM: Data, csrPEM: Data) throws -> Data {
        let privateDER = try pem(privateKeyPEM, label: "RSA PRIVATE KEY")
        let csr = try pem(csrPEM, label: "CERTIFICATE REQUEST")
        let privateKey = try key(privateDER, privateKey: true)
        guard let publicKey = SecKeyCopyPublicKey(privateKey) else { throw CertificateIssuanceFailure.keyMismatch }
        let publicBytes = try external(publicKey)
        var outer = Reader(csr)
        let sequence = try outer.read(0x30)
        try outer.requireEnd()
        var request = Reader(sequence.value)
        let info = try request.read(0x30)
        let algorithm = try request.read(0x30)
        let signature = try request.read(0x03)
        try request.requireEnd()
        guard algorithm.encoded == sha256RSA, signature.value.first == 0, signature.value.count > 1 else {
            throw CertificateIssuanceFailure.invalidRecord
        }
        var fields = Reader(info.value)
        guard try fields.read(0x02).value == Data([0]) else { throw CertificateIssuanceFailure.invalidRecord }
        _ = try fields.read(0x30) // Subject is signed; no identity claims derived from it.
        let spki = try fields.read(0x30)
        let attributes = try fields.read(0xa0)
        try fields.requireEnd()
        guard attributes.value.isEmpty else { throw CertificateIssuanceFailure.invalidRecord }
        var spkiFields = Reader(spki.value)
        guard try spkiFields.read(0x30).encoded == rsaAlgorithm else { throw CertificateIssuanceFailure.invalidRecord }
        let bits = try spkiFields.read(0x03).value
        try spkiFields.requireEnd()
        guard bits.first == 0, bits.count > 1 else { throw CertificateIssuanceFailure.invalidRecord }
        let csrKey = try key(Data(bits.dropFirst()), privateKey: false)
        guard try external(csrKey) == publicBytes else { throw CertificateIssuanceFailure.keyMismatch }
        guard SecKeyVerifySignature(csrKey, .rsaSignatureMessagePKCS1v15SHA256,
                                    info.encoded as CFData, Data(signature.value.dropFirst()) as CFData, nil) else {
            throw CertificateIssuanceFailure.keyMismatch
        }
        return publicBytes
    }

    public static func certificatePublicKey(_ der: Data) throws -> Data {
        guard !der.isEmpty, der.count <= 16_384 else { throw CertificateIssuanceFailure.invalidRecord }
        var reader = Reader(der); _ = try reader.read(0x30); try reader.requireEnd()
        guard let certificate = SecCertificateCreateWithData(nil, der as CFData),
              let key = SecCertificateCopyKey(certificate) else { throw CertificateIssuanceFailure.invalidRecord }
        try requireRSA(key)
        return try external(key)
    }

    private static func pem(_ data: Data, label: String) throws -> Data {
        guard !data.isEmpty, data.count <= 8192, let text = String(data: data, encoding: .ascii) else {
            throw CertificateIssuanceFailure.invalidRecord
        }
        var lines = text.trimmingCharacters(in: .whitespacesAndNewlines).components(separatedBy: .newlines)
        lines = lines.filter { !$0.isEmpty }
        guard lines.count >= 3, lines.first == "-----BEGIN \(label)-----", lines.last == "-----END \(label)-----",
              let decoded = Data(base64Encoded: lines.dropFirst().dropLast().joined()), !decoded.isEmpty else {
            throw CertificateIssuanceFailure.invalidRecord
        }
        return decoded
    }
    private static func key(_ bytes: Data, privateKey: Bool) throws -> SecKey {
        let attributes: [String: Any] = [kSecAttrKeyType as String: kSecAttrKeyTypeRSA,
            kSecAttrKeyClass as String: privateKey ? kSecAttrKeyClassPrivate : kSecAttrKeyClassPublic]
        guard let key = SecKeyCreateWithData(bytes as CFData, attributes as CFDictionary, nil) else {
            throw CertificateIssuanceFailure.invalidRecord
        }
        try requireRSA(key)
        return key
    }
    private static func requireRSA(_ key: SecKey) throws {
        guard let attrs = SecKeyCopyAttributes(key) as? [String: Any],
              attrs[kSecAttrKeyType as String] as? String == kSecAttrKeyTypeRSA as String,
              let size = attrs[kSecAttrKeySizeInBits as String] as? Int, size >= 2048, size <= 4096 else {
            throw CertificateIssuanceFailure.invalidRecord
        }
    }
    private static func external(_ key: SecKey) throws -> Data {
        guard let data = SecKeyCopyExternalRepresentation(key, nil) as Data?, !data.isEmpty, data.count <= 2048 else {
            throw CertificateIssuanceFailure.keyMismatch
        }
        return data
    }
    private struct Reader {
        let bytes: [UInt8]
        var offset = 0
        init(_ data: Data) { bytes = Array(data) }
        mutating func read(_ tag: UInt8) throws -> (value: Data, encoded: Data) {
            let start = offset
            guard offset <= bytes.count - 2, bytes[offset] == tag else { throw CertificateIssuanceFailure.invalidRecord }
            offset += 1
            let marker = Int(bytes[offset]); offset += 1
            var length = marker
            if marker >= 128 {
                let count = marker & 0x7f
                guard count > 0, count <= 4, count <= bytes.count - offset, bytes[offset] != 0 else {
                    throw CertificateIssuanceFailure.invalidRecord
                }
                length = 0
                for _ in 0..<count { length = (length << 8) | Int(bytes[offset]); offset += 1 }
                guard length >= 128 else { throw CertificateIssuanceFailure.invalidRecord }
            }
            guard length <= bytes.count - offset else { throw CertificateIssuanceFailure.invalidRecord }
            let value = Data(bytes[offset..<(offset + length)]); offset += length
            return (value, Data(bytes[start..<offset]))
        }
        func requireEnd() throws {
            guard offset == bytes.count else { throw CertificateIssuanceFailure.invalidRecord }
        }
    }
}
#endif
