# SPDX-License-Identifier: AGPL-3.0-only
"""Fail-closed native-symbol adaptation of one exact privacy-prepared gateway.

This is a build-time source transformation, not a runtime alias or ABI shim.
Only 244 reviewed Swift code-token byte spans change. Comments, string text,
interpolations outside those code tokens, parser behavior and service lifetimes
remain byte-identical. The full preimage and postimage are authenticated.

Source: SideStore/minimuxer, commit 12be70dc2627307a16bfd2dc7a009080d5bec909,
DeviceGateway/idevice/IdeviceGateway.swift, privacy-prepared by pairing_safety.py.
Upstream copyright is preserved in the accompanying fixture and repository license.
"""
from __future__ import annotations

from collections import Counter
import hashlib

GATEWAY_PATH = "Dependencies/minimuxer/DeviceGateway/idevice/IdeviceGateway.swift"
PREIMAGE_SHA256 = "1b66301e4ae70268ca3966639feed46271858265aa16a687dc4b144cf5179fb0"
POSTIMAGE_SHA256 = "33cf02fbaf234a43e983dc590a5cf54fcaf24328e7e107593614dc2a20a6c08f"
NAMESPACE_MAP_SHA256 = "af7b427e402a76a3cfd3e3522a57e483ced59ce520b8338a84592b0ecff4f615"
OCCURRENCE_COUNT = 244
IDENTIFIER_COUNT = 102

# The same linker/header names as the reviewed producer map. There are no aliases.
RENAMES = {
    'PLIST_ERR_SUCCESS': 'TETHERLESS_NATIVE_PLIST_ERR_SUCCESS',
    'adapter_free': 'tetherless_native_adapter_free',
    'afc_client_connect': 'tetherless_native_afc_client_connect',
    'afc_client_connect_rsd': 'tetherless_native_afc_client_connect_rsd',
    'afc_client_free': 'tetherless_native_afc_client_free',
    'afc_file_close': 'tetherless_native_afc_file_close',
    'afc_file_info_free': 'tetherless_native_afc_file_info_free',
    'afc_file_open': 'tetherless_native_afc_file_open',
    'afc_file_read_data_free': 'tetherless_native_afc_file_read_data_free',
    'afc_file_read_entire': 'tetherless_native_afc_file_read_entire',
    'afc_file_write': 'tetherless_native_afc_file_write',
    'afc_get_file_info': 'tetherless_native_afc_get_file_info',
    'afc_list_directory': 'tetherless_native_afc_list_directory',
    'afc_make_directory': 'tetherless_native_afc_make_directory',
    'afc_remove_path': 'tetherless_native_afc_remove_path',
    'debug_proxy_connect_rsd': 'tetherless_native_debug_proxy_connect_rsd',
    'debug_proxy_free': 'tetherless_native_debug_proxy_free',
    'debug_proxy_new': 'tetherless_native_debug_proxy_new',
    'debug_proxy_send_command': 'tetherless_native_debug_proxy_send_command',
    'debug_proxy_set_argv': 'tetherless_native_debug_proxy_set_argv',
    'debugserver_command_free': 'tetherless_native_debugserver_command_free',
    'debugserver_command_new': 'tetherless_native_debugserver_command_new',
    'heartbeat_client_free': 'tetherless_native_heartbeat_client_free',
    'heartbeat_connect': 'tetherless_native_heartbeat_connect',
    'heartbeat_connect_rsd': 'tetherless_native_heartbeat_connect_rsd',
    'heartbeat_get_marco': 'tetherless_native_heartbeat_get_marco',
    'heartbeat_send_polo': 'tetherless_native_heartbeat_send_polo',
    'house_arrest_client_connect': 'tetherless_native_house_arrest_client_connect',
    'house_arrest_client_connect_rsd': 'tetherless_native_house_arrest_client_connect_rsd',
    'house_arrest_vend_container': 'tetherless_native_house_arrest_vend_container',
    'idevice_data_free': 'tetherless_native_idevice_data_free',
    'idevice_error_free': 'tetherless_native_idevice_error_free',
    'idevice_free': 'tetherless_native_idevice_free',
    'idevice_init_logger': 'tetherless_native_idevice_init_logger',
    'idevice_pairing_file_free': 'tetherless_native_idevice_pairing_file_free',
    'idevice_pairing_file_from_bytes': 'tetherless_native_idevice_pairing_file_from_bytes',
    'idevice_provider_free': 'tetherless_native_idevice_provider_free',
    'idevice_provider_get_pairing_file': 'tetherless_native_idevice_provider_get_pairing_file',
    'idevice_stream_free': 'tetherless_native_idevice_stream_free',
    'idevice_string_free': 'tetherless_native_idevice_string_free',
    'idevice_tcp_provider_new': 'tetherless_native_idevice_tcp_provider_new',
    'idevice_to_stream': 'tetherless_native_idevice_to_stream',
    'idevice_usbmuxd_addr_free': 'tetherless_native_idevice_usbmuxd_addr_free',
    'idevice_usbmuxd_connect_to_device': 'tetherless_native_idevice_usbmuxd_connect_to_device',
    'idevice_usbmuxd_connection_free': 'tetherless_native_idevice_usbmuxd_connection_free',
    'idevice_usbmuxd_default_addr_new': 'tetherless_native_idevice_usbmuxd_default_addr_new',
    'idevice_usbmuxd_device_get_device_id': 'tetherless_native_idevice_usbmuxd_device_get_device_id',
    'idevice_usbmuxd_device_get_udid': 'tetherless_native_idevice_usbmuxd_device_get_udid',
    'idevice_usbmuxd_device_list_free': 'tetherless_native_idevice_usbmuxd_device_list_free',
    'idevice_usbmuxd_get_devices': 'tetherless_native_idevice_usbmuxd_get_devices',
    'idevice_usbmuxd_new_default_connection': 'tetherless_native_idevice_usbmuxd_new_default_connection',
    'idevice_usbmuxd_tcp_addr_new': 'tetherless_native_idevice_usbmuxd_tcp_addr_new',
    'idevice_usbmuxd_unix_addr_new': 'tetherless_native_idevice_usbmuxd_unix_addr_new',
    'image_mounter_connect': 'tetherless_native_image_mounter_connect',
    'image_mounter_connect_rsd': 'tetherless_native_image_mounter_connect_rsd',
    'image_mounter_copy_devices': 'tetherless_native_image_mounter_copy_devices',
    'image_mounter_free': 'tetherless_native_image_mounter_free',
    'image_mounter_mount_image': 'tetherless_native_image_mounter_mount_image',
    'image_mounter_mount_personalized': 'tetherless_native_image_mounter_mount_personalized',
    'image_mounter_mount_personalized_rsd': 'tetherless_native_image_mounter_mount_personalized_rsd',
    'image_mounter_upload_image': 'tetherless_native_image_mounter_upload_image',
    'installation_proxy_client_free': 'tetherless_native_installation_proxy_client_free',
    'installation_proxy_connect': 'tetherless_native_installation_proxy_connect',
    'installation_proxy_connect_rsd': 'tetherless_native_installation_proxy_connect_rsd',
    'installation_proxy_get_apps': 'tetherless_native_installation_proxy_get_apps',
    'installation_proxy_install': 'tetherless_native_installation_proxy_install',
    'installation_proxy_uninstall': 'tetherless_native_installation_proxy_uninstall',
    'lockdownd_client_free': 'tetherless_native_lockdownd_client_free',
    'lockdownd_connect': 'tetherless_native_lockdownd_connect',
    'lockdownd_connect_rsd': 'tetherless_native_lockdownd_connect_rsd',
    'lockdownd_get_value': 'tetherless_native_lockdownd_get_value',
    'lockdownd_start_service': 'tetherless_native_lockdownd_start_service',
    'lockdownd_start_session': 'tetherless_native_lockdownd_start_session',
    'misagent_client_free': 'tetherless_native_misagent_client_free',
    'misagent_connect': 'tetherless_native_misagent_connect',
    'misagent_connect_rsd': 'tetherless_native_misagent_connect_rsd',
    'misagent_copy_all': 'tetherless_native_misagent_copy_all',
    'misagent_free_profiles': 'tetherless_native_misagent_free_profiles',
    'misagent_install': 'tetherless_native_misagent_install',
    'misagent_remove': 'tetherless_native_misagent_remove',
    'pairable_host_accept_fd': 'tetherless_native_pairable_host_accept_fd',
    'pairable_host_free': 'tetherless_native_pairable_host_free',
    'pairable_host_prepare': 'tetherless_native_pairable_host_prepare',
    'plist_dict_get_item': 'tetherless_native_plist_dict_get_item',
    'plist_dict_set_item': 'tetherless_native_plist_dict_set_item',
    'plist_free': 'tetherless_native_plist_free',
    'plist_get_string_val': 'tetherless_native_plist_get_string_val',
    'plist_get_uint_val': 'tetherless_native_plist_get_uint_val',
    'plist_new_dict': 'tetherless_native_plist_new_dict',
    'plist_new_string': 'tetherless_native_plist_new_string',
    'plist_t': 'tetherless_native_plist_t',
    'plist_to_xml': 'tetherless_native_plist_to_xml',
    'rp_pairing_file_free': 'tetherless_native_rp_pairing_file_free',
    'rp_pairing_file_from_bytes': 'tetherless_native_rp_pairing_file_from_bytes',
    'rp_pairing_file_generate': 'tetherless_native_rp_pairing_file_generate',
    'rp_pairing_file_to_bytes': 'tetherless_native_rp_pairing_file_to_bytes',
    'rp_pairing_file_write': 'tetherless_native_rp_pairing_file_write',
    'rppairing_pair_network': 'tetherless_native_rppairing_pair_network',
    'rppairing_peer_device_free': 'tetherless_native_rppairing_peer_device_free',
    'rsd_handshake_free': 'tetherless_native_rsd_handshake_free',
    'tunnel_create_rppairing_with_options': 'tetherless_native_tunnel_create_rppairing_with_options',
    'usbmuxd_provider_new': 'tetherless_native_usbmuxd_provider_new',
}

# Absolute UTF-8 byte offsets in PREIMAGE_SHA256, not character offsets.
# Function values passed to the service helpers are included, not only calls.
TOKEN_SPANS = (
    (1106, 'plist_t'),
    (1190, 'plist_get_string_val'),
    (1852, 'idevice_error_free'),
    (1933, 'plist_t'),
    (2072, 'plist_free'),
    (2627, 'rp_pairing_file_free'),
    (2698, 'idevice_pairing_file_free'),
    (3315, 'rsd_handshake_free'),
    (3435, 'adapter_free'),
    (4024, 'idevice_init_logger'),
    (5198, 'rp_pairing_file_from_bytes'),
    (6204, 'idevice_pairing_file_from_bytes'),
    (10360, 'tunnel_create_rppairing_with_options'),
    (11148, 'idevice_error_free'),
    (13970, 'idevice_error_free'),
    (15260, 'idevice_error_free'),
    (18124, 'idevice_usbmuxd_tcp_addr_new'),
    (18591, 'idevice_usbmuxd_unix_addr_new'),
    (18898, 'idevice_usbmuxd_default_addr_new'),
    (19196, 'idevice_error_free'),
    (19762, 'idevice_usbmuxd_new_default_connection'),
    (20083, 'idevice_error_free'),
    (20125, 'idevice_usbmuxd_addr_free'),
    (20330, 'idevice_usbmuxd_connection_free'),
    (20497, 'idevice_usbmuxd_get_devices'),
    (20822, 'idevice_error_free'),
    (20867, 'idevice_usbmuxd_addr_free'),
    (21244, 'idevice_usbmuxd_device_list_free'),
    (21325, 'idevice_usbmuxd_device_get_udid'),
    (21398, 'idevice_usbmuxd_device_get_device_id'),
    (21604, 'usbmuxd_provider_new'),
    (21755, 'idevice_string_free'),
    (21956, 'idevice_usbmuxd_addr_free'),
    (22241, 'idevice_usbmuxd_addr_free'),
    (22654, 'idevice_error_free'),
    (23179, 'idevice_provider_free'),
    (23626, 'idevice_error_free'),
    (25387, 'idevice_pairing_file_from_bytes'),
    (26346, 'idevice_tcp_provider_new'),
    (27144, 'idevice_provider_free'),
    (29667, 'lockdownd_connect_rsd'),
    (29719, 'lockdownd_connect'),
    (29759, 'lockdownd_client_free'),
    (30073, 'idevice_pairing_file_from_bytes'),
    (30571, 'idevice_pairing_file_free'),
    (30746, 'lockdownd_start_session'),
    (31530, 'plist_t'),
    (31669, 'lockdownd_get_value'),
    (33387, 'misagent_connect_rsd'),
    (33438, 'misagent_connect'),
    (33477, 'misagent_client_free'),
    (33866, 'misagent_install'),
    (34758, 'misagent_connect_rsd'),
    (34809, 'misagent_connect'),
    (34848, 'misagent_client_free'),
    (35101, 'misagent_remove'),
    (35902, 'installation_proxy_connect_rsd'),
    (35963, 'installation_proxy_connect'),
    (36012, 'installation_proxy_client_free'),
    (36288, 'installation_proxy_uninstall'),
    (36600, 'idevice_error_free'),
    (37175, 'afc_client_connect_rsd'),
    (37228, 'afc_client_connect'),
    (37269, 'afc_client_free'),
    (37591, 'afc_make_directory'),
    (37851, 'afc_make_directory'),
    (38154, 'afc_file_open'),
    (38469, 'idevice_error_free'),
    (38752, 'afc_file_close'),
    (39087, 'afc_file_write'),
    (39391, 'idevice_error_free'),
    (39933, 'installation_proxy_connect_rsd'),
    (39994, 'installation_proxy_connect'),
    (40043, 'installation_proxy_client_free'),
    (40385, 'installation_proxy_install'),
    (40684, 'idevice_error_free'),
    (41253, 'afc_client_connect_rsd'),
    (41306, 'afc_client_connect'),
    (41347, 'afc_client_free'),
    (41643, 'afc_make_directory'),
    (41909, 'afc_make_directory'),
    (42202, 'afc_make_directory'),
    (43170, 'afc_make_directory'),
    (43408, 'afc_file_open'),
    (43650, 'idevice_error_free'),
    (43948, 'afc_file_close'),
    (44395, 'afc_file_write'),
    (44639, 'idevice_error_free'),
    (45365, 'installation_proxy_connect_rsd'),
    (45426, 'installation_proxy_connect'),
    (45475, 'installation_proxy_client_free'),
    (45839, 'plist_new_dict'),
    (45880, 'plist_free'),
    (45918, 'plist_dict_set_item'),
    (45962, 'plist_new_string'),
    (46027, 'installation_proxy_install'),
    (46336, 'idevice_error_free'),
    (46904, 'installation_proxy_connect_rsd'),
    (46965, 'installation_proxy_connect'),
    (47014, 'installation_proxy_client_free'),
    (47442, 'installation_proxy_get_apps'),
    (47750, 'idevice_error_free'),
    (48369, 'plist_t'),
    (48664, 'plist_dict_get_item'),
    (49127, 'plist_dict_get_item'),
    (49556, 'plist_dict_get_item'),
    (50905, 'debugserver_command_new'),
    (51036, 'debugserver_command_free'),
    (51263, 'debug_proxy_send_command'),
    (51563, 'idevice_error_free'),
    (52649, 'lockdownd_connect_rsd'),
    (52701, 'lockdownd_connect'),
    (52741, 'lockdownd_client_free'),
    (53004, 'lockdownd_start_service'),
    (53281, 'idevice_error_free'),
    (53703, 'idevice_usbmuxd_default_addr_new'),
    (53881, 'idevice_error_free'),
    (54184, 'idevice_usbmuxd_addr_free'),
    (54280, 'idevice_usbmuxd_new_default_connection'),
    (54473, 'idevice_error_free'),
    (54775, 'idevice_usbmuxd_connection_free'),
    (54931, 'idevice_usbmuxd_get_devices'),
    (55114, 'idevice_error_free'),
    (55466, 'idevice_usbmuxd_device_list_free'),
    (55541, 'idevice_usbmuxd_device_get_device_id'),
    (55715, 'idevice_usbmuxd_connect_to_device'),
    (55950, 'idevice_error_free'),
    (56280, 'idevice_free'),
    (56374, 'idevice_to_stream'),
    (56557, 'idevice_error_free'),
    (56914, 'debug_proxy_new'),
    (57163, 'idevice_error_free'),
    (57206, 'idevice_stream_free'),
    (57434, 'idevice_stream_free'),
    (57941, 'debug_proxy_free'),
    (58630, 'debug_proxy_set_argv'),
    (58936, 'idevice_error_free'),
    (60233, 'debug_proxy_connect_rsd'),
    (60283, 'debug_proxy_free'),
    (61966, 'debug_proxy_connect_rsd'),
    (62016, 'debug_proxy_free'),
    (62802, 'misagent_connect_rsd'),
    (62853, 'misagent_connect'),
    (62892, 'misagent_client_free'),
    (63269, 'misagent_copy_all'),
    (63555, 'idevice_error_free'),
    (65601, 'misagent_free_profiles'),
    (66069, 'heartbeat_connect_rsd'),
    (66120, 'heartbeat_connect'),
    (66159, 'heartbeat_client_free'),
    (66352, 'heartbeat_get_marco'),
    (66620, 'idevice_error_free'),
    (66885, 'heartbeat_send_polo'),
    (67133, 'idevice_error_free'),
    (68146, 'lockdownd_connect_rsd'),
    (68202, 'lockdownd_client_free'),
    (68315, 'plist_t'),
    (68445, 'lockdownd_get_value'),
    (68672, 'idevice_error_free'),
    (68875, 'plist_free'),
    (68950, 'plist_get_uint_val'),
    (69174, 'image_mounter_connect_rsd'),
    (69210, 'image_mounter_free'),
    (69842, 'image_mounter_mount_personalized_rsd'),
    (70755, 'idevice_error_free'),
    (71945, 'idevice_pairing_file_from_bytes'),
    (73027, 'idevice_tcp_provider_new'),
    (73752, 'idevice_provider_free'),
    (73997, 'lockdownd_connect'),
    (74225, 'idevice_error_free'),
    (74710, 'lockdownd_client_free'),
    (74789, 'plist_t'),
    (74911, 'lockdownd_get_value'),
    (75140, 'idevice_error_free'),
    (75243, 'idevice_provider_get_pairing_file'),
    (75365, 'idevice_error_free'),
    (75729, 'idevice_pairing_file_free'),
    (75794, 'lockdownd_start_session'),
    (76002, 'idevice_error_free'),
    (76239, 'lockdownd_get_value'),
    (76478, 'idevice_error_free'),
    (76704, 'plist_free'),
    (76746, 'plist_dict_get_item'),
    (77065, 'plist_get_uint_val'),
    (77393, 'image_mounter_connect'),
    (77626, 'idevice_error_free'),
    (78013, 'image_mounter_free'),
    (78582, 'image_mounter_mount_personalized'),
    (79397, 'idevice_error_free'),
    (79934, 'image_mounter_connect_rsd'),
    (79990, 'image_mounter_connect'),
    (80034, 'image_mounter_free'),
    (80338, 'plist_t'),
    (80405, 'image_mounter_copy_devices'),
    (80875, 'idevice_error_free'),
    (81153, 'plist_free'),
    (82166, 'plist_t'),
    (82289, 'plist_to_xml'),
    (82347, 'PLIST_ERR_SUCCESS'),
    (82813, 'image_mounter_connect_rsd'),
    (82869, 'image_mounter_connect'),
    (82913, 'image_mounter_free'),
    (83254, 'image_mounter_upload_image'),
    (83844, 'idevice_error_free'),
    (84338, 'image_mounter_mount_image'),
    (84891, 'idevice_error_free'),
    (85410, 'rp_pairing_file_generate'),
    (85599, 'idevice_error_free'),
    (86080, 'rp_pairing_file_to_bytes'),
    (86286, 'idevice_error_free'),
    (86331, 'rp_pairing_file_free'),
    (86619, 'idevice_data_free'),
    (87124, 'rp_pairing_file_free'),
    (87696, 'rp_pairing_file_write'),
    (87889, 'idevice_error_free'),
    (88259, 'rp_pairing_file_to_bytes'),
    (88489, 'idevice_error_free'),
    (88945, 'idevice_data_free'),
    (91129, 'pairable_host_prepare'),
    (91491, 'idevice_error_free'),
    (91905, 'pairable_host_free'),
    (91996, 'idevice_string_free'),
    (92199, 'idevice_data_free'),
    (93522, 'pairable_host_accept_fd'),
    (94201, 'idevice_error_free'),
    (94576, 'rp_pairing_file_free'),
    (94772, 'rppairing_peer_device_free'),
    (98187, 'rp_pairing_file_free'),
    (99439, 'rppairing_pair_network'),
    (101041, 'idevice_error_free'),
    (101344, 'rppairing_peer_device_free'),
    (102752, 'house_arrest_client_connect_rsd'),
    (102814, 'house_arrest_client_connect'),
    (103177, 'house_arrest_vend_container'),
    (104386, 'afc_list_directory'),
    (105039, 'idevice_string_free'),
    (105517, 'afc_file_open'),
    (106086, 'afc_file_close'),
    (106238, 'afc_file_read_entire'),
    (106755, 'afc_file_read_data_free'),
    (107348, 'afc_get_file_info'),
    (107738, 'afc_file_info_free'),
    (109520, 'afc_remove_path'),
    (110508, 'afc_client_free'),
)

def transform_gateway(data: bytes) -> bytes:
    """Return the exact namespaced postimage; reject every other input or plan."""
    if type(data) is not bytes or hashlib.sha256(data).hexdigest() != PREIMAGE_SHA256:
        raise ValueError("Rust gateway differs from the exact privacy-prepared preimage")
    counts = Counter(name for _, name in TOKEN_SPANS)
    if (len(TOKEN_SPANS) != OCCURRENCE_COUNT or len(counts) != IDENTIFIER_COUNT
            or set(counts) != set(RENAMES) or len(set(RENAMES.values())) != IDENTIFIER_COUNT):
        raise ValueError("Rust gateway namespace plan differs")
    parts = []
    cursor = 0
    for offset, name in TOKEN_SPANS:
        old = name.encode("ascii")
        new = RENAMES[name].encode("ascii")
        if (offset < cursor or data[offset:offset + len(old)] != old
                or new != (("TETHERLESS_NATIVE_" if name.isupper() else "tetherless_native_") + name).encode("ascii")):
            raise ValueError("Rust gateway namespace span differs")
        parts.extend((data[cursor:offset], new))
        cursor = offset + len(old)
    parts.append(data[cursor:])
    result = b"".join(parts)
    if hashlib.sha256(result).hexdigest() != POSTIMAGE_SHA256:
        raise ValueError("Rust gateway differs from the exact namespaced postimage")
    return result
